[package]
name    = "svc-cargo"
version = "0.1.0"
edition = "2021"      # Allowed values are 2015, 2018, 2021
# Rust Editions: https://doc.rust-lang.org/edition-guide/index.html

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum              = "0.5.15"
cargo-husky       = "1"
chrono            = { version = "0.4.22", features = ["serde"] }
hyper             = "0.14.20"
prost             = "0.11.0"
prost-build       = "0.11.1"
prost-types       = "0.11.1"
serde             = "1.0.144"
serde_json        = "1.0.85"
svc-cargo-client  = { git = "https://github.com/Arrow-air/svc-scheduler/", branch = "develop" }
tokio             = { version = "1.20.1", features = ["full"] }
tokio-util        = "0.7.3"
utoipa            = { version = "2.1.0", features = ["axum_extras"] }
utoipa-swagger-ui = { version = "2.0.1", features = ["axum"] }

[build-dependencies]
tonic-build = "0.8"

[lib]
name = "svc_cargo_api_rest"
path = "src/api_rest.rs"
