[package]
description = "Arrow cargo service GRPC server"
edition     = "2021"                                                       # Allowed values are 2015, 2018, 2021
homepage    = "https://www.arrowair.com/docs/documentation/services/intro"
keywords    = ["vtol", "server", "cargo"]                                  # max 5
license     = "BUSL-1.1"
name        = "svc-cargo"
repository  = "https://github.com/Arrow-air/svc-cargo"
version     = "0.2.0"

categories = [
  "aerospace::drones",
  "aerospace::protocols",
] # max 5 -- https://crates.io/category_slugs

[features]
vendored-openssl = ['openssl/vendored']

[dependencies]
axum                      = "0.5"
cargo-husky               = "1"
chrono                    = { version = "0.4", features = ["serde"] }
env_logger                = "0.9"
futures                   = "0.3"
hyper                     = "0.14"
log                       = "0.4"
openssl                   = "0.10"
prost                     = "0.11"
prost-build               = "0.11"
prost-types               = "0.11"
serde                     = "1.0"
serde_json                = "1.0"
svc-pricing-client-grpc   = { git = "https://github.com/Arrow-air/svc-pricing", branch = "main" }
svc-scheduler-client-grpc = { git = "https://github.com/Arrow-air/svc-scheduler", branch = "main" }
svc-storage-client-grpc   = { git = "https://github.com/Arrow-air/svc-storage", branch = "main" }
tokio                     = { version = "1.20", features = ["full"] }
tokio-util                = "0.7"
tonic                     = "0.8"
tonic-health              = "0.7"
utoipa                    = { version = "2.1", features = ["axum_extras"] }
utoipa-swagger-ui         = { version = "2.0", features = ["axum"] }
uuid                      = { version = "1.2", features = ["v4"] }

[build-dependencies]
tonic-build = "0.8"

[dependencies.log4rs]
features = [
  "background_rotation",
  "rolling_file_appender",
  "json_format",
  "gzip",
]
version = "1.2"
