[package]
edition = "2021"
name    = "svc-cargo-client-rest"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono     = { version = "0.4", features = ["serde"] }
serde      = "1.0"
serde_json = "1.0"

[dependencies.utoipa]
features = ["axum_extras", "chrono"]
version  = "2.2"

[[example]]
name = "rest"

[dev-dependencies]
hyper = { version = "0.14", features = ["full"] }
tokio = { version = "1.20", features = ["full"] }
uuid  = { version = "1.3.0", features = ["v4"] }
